using System.Globalization;
using System.Text;
using System.Text.Json;
using Patsanstha.Modules.Reporting.Application.Abstractions;

namespace Patsanstha.Modules.Reporting.Application.ReportSnapshots.DownloadReportSnapshot;

public static class ReportExportFormatter
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public static ReportExportFileDto Format(ReportSnapshotDetailDto snapshot, ReportExportFormat format) =>
        format switch
        {
            ReportExportFormat.Json => FormatJson(snapshot),
            ReportExportFormat.Csv => FormatCsv(snapshot),
            _ => throw new ArgumentOutOfRangeException(nameof(format), format, null),
        };

    public static string BuildFileName(ReportSnapshotDetailDto snapshot, ReportExportFormat format)
    {
        var slug = Slugify(snapshot.Title);
        var date = snapshot.GeneratedAt.UtcDateTime.ToString("yyyyMMdd", CultureInfo.InvariantCulture);
        var extension = format == ReportExportFormat.Json ? "json" : "csv";
        return $"{slug}-{date}.{extension}";
    }

    private static ReportExportFileDto FormatJson(ReportSnapshotDetailDto snapshot)
    {
        var parameters = DeserializeJsonElement(snapshot.ParametersJson);
        var result = DeserializeJsonElement(snapshot.ResultJson);
        var payload = new
        {
            snapshot.Id,
            reportType = snapshot.ReportType.ToString(),
            snapshot.Title,
            generatedAt = snapshot.GeneratedAt,
            generatedByUserId = snapshot.GeneratedByUserId,
            status = snapshot.Status.ToString(),
            parameters,
            result,
        };

        var json = JsonSerializer.Serialize(payload, JsonOptions);
        var bytes = Encoding.UTF8.GetBytes(json);
        return new ReportExportFileDto(bytes, "application/json", BuildFileName(snapshot, ReportExportFormat.Json));
    }

    private static ReportExportFileDto FormatCsv(ReportSnapshotDetailDto snapshot)
    {
        var builder = new StringBuilder();
        WriteRow(builder, "Field", "Value");
        WriteRow(builder, "Report Title", snapshot.Title);
        WriteRow(builder, "Report Type", snapshot.ReportType.ToString());
        WriteRow(builder, "Status", snapshot.Status.ToString());
        WriteRow(builder, "Generated At", snapshot.GeneratedAt.ToString("O", CultureInfo.InvariantCulture));
        WriteRow(builder, "Generated By User Id", snapshot.GeneratedByUserId?.ToString() ?? string.Empty);
        builder.AppendLine();

        using var resultDocument = ParseJson(snapshot.ResultJson);
        var result = resultDocument.RootElement;
        if (result.ValueKind == JsonValueKind.Object)
        {
            var arrayProperties = new List<(string Name, JsonElement Value)>();
            foreach (var property in result.EnumerateObject())
            {
                if (property.Value.ValueKind == JsonValueKind.Array)
                {
                    arrayProperties.Add((property.Name, property.Value));
                    continue;
                }

                WriteRow(builder, FormatLabel(property.Name), FormatScalar(property.Value));
            }

            foreach (var (name, array) in arrayProperties)
            {
                builder.AppendLine();
                builder.AppendLine(FormatLabel(name));
                WriteArraySection(builder, array);
            }
        }
        else
        {
            WriteRow(builder, "Result", snapshot.ResultJson);
        }

        var bytes = Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(builder.ToString())).ToArray();
        return new ReportExportFileDto(bytes, "text/csv", BuildFileName(snapshot, ReportExportFormat.Csv));
    }

    private static void WriteArraySection(StringBuilder builder, JsonElement array)
    {
        if (array.ValueKind != JsonValueKind.Array)
        {
            WriteRow(builder, "Value", FormatScalar(array));
            return;
        }

        var items = array.EnumerateArray().ToList();
        if (items.Count == 0)
        {
            builder.AppendLine("(no rows)");
            return;
        }

        if (items[0].ValueKind != JsonValueKind.Object)
        {
            WriteRow(builder, "Value");
            foreach (var item in items)
            {
                WriteRow(builder, FormatScalar(item));
            }

            return;
        }

        var headers = items
            .SelectMany(item => item.EnumerateObject().Select(property => property.Name))
            .Distinct(StringComparer.Ordinal)
            .ToList();

        WriteRow(builder, headers.Select(FormatLabel).ToArray());
        foreach (var item in items)
        {
            WriteRow(builder, headers.Select(header => FormatScalar(item.TryGetProperty(header, out var value) ? value : default)).ToArray());
        }
    }

    private static JsonElement DeserializeJsonElement(string json) =>
        JsonSerializer.Deserialize<JsonElement>(string.IsNullOrWhiteSpace(json) ? "{}" : json);

    private static JsonDocument ParseJson(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return JsonDocument.Parse("{}");
        }

        return JsonDocument.Parse(json);
    }

    private static string FormatLabel(string name) =>
        string.Concat(name.Select((character, index) =>
            index > 0 && char.IsUpper(character) ? " " + character : character.ToString())).Trim();

    private static string FormatScalar(JsonElement value) =>
        value.ValueKind switch
        {
            JsonValueKind.String => value.GetString() ?? string.Empty,
            JsonValueKind.Number => value.GetRawText(),
            JsonValueKind.True => "Yes",
            JsonValueKind.False => "No",
            JsonValueKind.Null or JsonValueKind.Undefined => string.Empty,
            JsonValueKind.Object or JsonValueKind.Array => value.GetRawText(),
            _ => value.ToString() ?? string.Empty,
        };

    private static void WriteRow(StringBuilder builder, params string[] values)
    {
        builder.AppendLine(string.Join(",", values.Select(EscapeCsv)));
    }

    private static string EscapeCsv(string? value)
    {
        var text = value ?? string.Empty;
        if (text.Contains('"') || text.Contains(',') || text.Contains('\n') || text.Contains('\r'))
        {
            return $"\"{text.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";
        }

        return text;
    }

    private static string Slugify(string title)
    {
        var chars = title
            .Trim()
            .ToLowerInvariant()
            .Where(character => char.IsLetterOrDigit(character) || character is ' ' or '-')
            .ToArray();

        var slug = new string(chars).Replace(' ', '-');
        while (slug.Contains("--", StringComparison.Ordinal))
        {
            slug = slug.Replace("--", "-", StringComparison.Ordinal);
        }

        return string.IsNullOrWhiteSpace(slug) ? "report" : slug.Trim('-');
    }
}
